<?php

namespace App\Models;

use App\Observers\FangOwnerObserver;

class FangOwner extends Base
{
    protected static function boot()
    {
        // ctrl+O
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(FangOwnerObserver::class);
    }
}
